### PR TITLE
Fixed a bug (RegExp.test is not a function)

### LINKED ISSUE #26: [BUG] TypeError during URL validation
**Describe the bug**

A type error occurs when attempting to save a product object into the db, when the object has URL-valued properties

**How to reproduce**
```js
let Product = require('./src/models/db/product');

let product = new Product({
      name: 'Product',
      description: 'The only product we sell currently',
      productImageLinks: [
        'http://google.no/image.png',
        'https://bing.com/image.png'
      ],
      quantityType: 'things',
      averageRating: 4.9,
      reviewCount: 999,
      category: 'Good products',
      price: 1.99,
      brandName: 'Supreme',
      brandLogoLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Supreme_Logo.svg/576px-Supreme_Logo.svg.png',
      discounts: [
        {
          name: '90% discount',
          type: 'percentage',
          value: 90
        },
        {
          name: '2% discount',
          type: 'percentage',
          value: 2
        }
      ]
    });

product.save().then(console.log).catch(console.log);
```

**Expected behavior**
No error and the product object should be logged to the console.

**Screenshots**
Something went wrong trying to upload it :(

**Device Information**
 - OS: Windows 10
 - Node version: v14.4.0

### PR DESCRIPTION
**Pull request by magnus195**
**Description**

This just converts the string into a RegExp

**Related Issue**

Closes #26 

**Additional Information**

I also simplified the sample data script a tiny bit

### CODE REVIEW

File: sampleDBData.js [hunk 1]
```diff
@@ -45,10 +45,6 @@ db.once('open', () => {
         }
       ]
     });
-
-    Product.collection.insertOne(product, (err, docs) => {
-      if (err) return console.error(err);
-      return console.log(docs);
-    });
+    product.save().then(console.log).catch(console.log);
```
Comment (snowteamer) [inline sampleDBData.js:48]: Logging every object to the console is very slow, but this is not a priority, it can wait until we have a solution using `.insertMany()`
